services:
  app:
    build: .
    container_name: moex_app
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/moex_app
      MOEX_TIMEOUT_SECONDS: 8
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: moex_db
    environment:
      POSTGRES_DB: moex_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
