apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moex
resources:
  - namespace.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - prometheus.yaml
  - loki.yaml
  - grafana.yaml
  - ingress.yaml
