apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: moex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: moex
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
